activation: tanh
attention: true
attention_head: 16
attention_size: 256
batch_size: 100
can_size: 17
cancer_type: true
dataset_name: dataset_CITRUS
dropout_rate: 0.2
embedding_size: 256
gep_normalization: scaleRow
gep_size: 5541
hidden_size: 320
input_dir: ./data
input_dropout_rate: 0.2
label: untitled
learning_rate: 0.005
mask01: true
max_fscore: 0.7
num_max_sga: 1396
output_dir: ./output
patience: 100
ppi: 0
run_count: '1'
sga_size: 11998
tag: ''
test_batch_size: 100
test_inc_size: 256
train_model: true
weight_decay: 1.0e-05
max_iter: 500

